name: Scraping CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  schedule:
    - cron: "0 0 * * *" # cada 24 horas

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: ci_cd_pipeline

    steps:
      - name: Checkout out repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        id: py381
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python src/app.py
